mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=tamnlt0908@@
    - MYSQL_DATABASE=shoppingCart
    - MYSQL_ROOT_PASSWORD=tamnlt0908@@
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"